name: Build wheels

on:
  workflow_dispatch:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # uncomment to force a wheel build
          ref: v5.2.0
          fetch-depth: 1

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.1
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: pp*
          CIBW_ARCHS_MACOS: "auto"
          CIBW_ARCHS_WINDOWS: "AMD64 x86"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BUILD_VERBOSITY: 2

      - name: Save wheels
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pypa/build
        run: pip install 'build[virtualenv]'

      - name: Build sdist
        run: python -m build --sdist

      - name: Save sdist
        uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: dist/*.tar.gz

  upload_all:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: publish_pypi
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: artifact-*
        merge-multiple: true
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.9.0
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
